Dev container tests (#1)
* add devcontaienr and test workflow

* disable old workflows for now

* branch typo

* use cached container for ruff format

* install pip requirements

* remove post create command.

* remove python version for now

* cat out  pip log

* don't ush lint step

* update python version

* create lint job to seperate

* needed runs-on

* must I checkotu each time?

* separate build and lint

* separate build and lint

* missed line

* be consistant

* add soem stuff to build the docs

* \

* add some logic to build-docs for validation runs and rename lint

* add back validation conditions

* add back docs pages

diff --git a/old-workflows/validate.yml b/old-workflows/validate.yml
--- a/old-workflows/validate.yml
+++ b/old-workflows/validate.yml
@@ -1,4 +1,5 @@
-name: 'validate' 
+---
+name: validate
 
 concurrency:
   group: validate
@@ -7,8 +8,8 @@ concurrency:
 on:
   push:
     branches:
-      - "**"
-      - "!main"
+      - '**'
+      - '!main'
   pull_request:
     types:
       - edited
@@ -21,6 +22,7 @@ permissions:
   contents: read
 
 jobs:
+
   # This job detects which parts of the repo have been changed, setting future jobs up for conditional behavior.
   detect-changes:
     runs-on: ubuntu-latest
@@ -47,24 +49,44 @@ jobs:
     runs-on: ubuntu-latest
     if: needs.detect-changes.outputs.tb_pulumi == 'true'
     steps:
-      - name: Checkout (GitHub)
-        uses: actions/checkout@v4
+      - uses: actions/checkout@v4
+
+      - name: Run Ruff syntax checks
+        uses: astral-sh/ruff-action@v3
+        with:
+          src: './tb_pulumi'
 
       - name: Run Ruff linter
-        uses: devcontainers/ci@v0.3
+        uses: astral-sh/ruff-action@v3
         with:
-          cacheFrom: ghcr.io/aatchison/pulumi/cached-devcontainer
-          runCmd: ruff format --check --diff
-          
+          src: './tb_pulumi'
+          args: 'format --check --diff'
+
   # Attempt to build the documentation. Fail if there are errors or warnings.
   build_docs:
     needs: detect-changes
     runs-on: ubuntu-latest
     if: needs.detect-changes.outputs.docs == 'true'
     steps:
-      - name: build docs
-        uses: devcontainers/ci@v0.3
+      - uses: actions/checkout@v4
+
+      - name: Install Python 3.13
+        uses: actions/setup-python@v5
         with:
-          cacheFrom: ghcr.io/aatchison/pulumi/cached-devcontainer
-          runCmd: ./build-docs.sh
-          
+          python-version: '3.13'
+
+      - name: Build docs
+        shell: bash
+        run: |
+          # GHA does `set -e` for us, but we expect the grep below to fail. Thus, we must `set +e` here.
+          set +e
+          pip install .[dev]
+          cd docs
+          make clean html |& tee make.log
+          grep '\(ERROR\|WARNING\)' make.log
+          if [ $? -eq 0 ]; then
+            echo "Problems found in docs build"
+            exit 1
+          else
+            exit 0
+          fi
