Overhaul CI

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -1,73 +1,63 @@
 ---
-name: deploy-staging-and-create-release
+name: release
 
 concurrency:
-  group: deploy-staging
+  group: release
   cancel-in-progress: true
 
-on:
-  push:  # Fix: on release
-    branches:
-      - main
+on: release
 
 permissions:
     contents: read
 
 jobs:
 
-  # This job detects which parts of the repo have been changed, setting future jobs up for conditional behavior.
-  detect-changes:
-    runs-on: ubuntu-latest
-    outputs:
-      docs: ${{ steps.check.outputs.docs }}
-    steps:
-      - uses: actions/checkout@v4
-
-      - uses: dorny/paths-filter@v3
-        id: check
-        with:
-          filters: |
-            docs:
-              - 'docs/**'
-
   detect-versions:
-    needs: detect-changes
-    if: needs.detect-changes.outputs.docs == 'true'
     runs-on: ubuntu-latest
     outputs:
       branch-exists: ${{ steps.branch-exists.outputs.exists }}
       version: v${{ steps.version.outputs.value }}
     steps:
-      # Detect version from pyproject.toml
       - uses: actions/checkout@v4
+
+      # Detect version from pyproject.toml
       - uses: SebRollen/toml-action@v1.2.0
         id: version
         with:
           file: './pyproject.toml'
           field: project.version
+
       - uses: GuillaumeFalourd/branch-exists@v1
         id: branch-exists
         with:
           branch: v${{ steps.version.outputs.value }}
+
+      - name: Fail on branch conflict
+        if: steps.branch-exists.outputs.exists == 'true'
+        shell: bash
+        run: |
+            echo "ERROR: A branch already exists called v${{ steps.version.outputs.value }}"
+            echo "       Update package.json to refer to a new version."
+            exit 1
 
 
   # The below code is commented out because it works, except for a Github auth issue.
   # Ref: https://github.com/orgs/community/discussions/13836
 
   # When the PR gets merged, cut a new version branch.
-  # merge:
-  #   needs: detect-versions
-  #   if: github.event.pull_request.merged == true && needs.detect-versions.outputs.branch-exists == 'false'
-  #   runs-on: ubuntu-latest
-  #   permissions:
-  #     contents: write
-  #   steps:
-  #     - uses: actions/checkout@v4
+  merge:
+    needs: detect-versions
+    if: needs.detect-versions.outputs.branch-exists == 'false'
+    runs-on: ubuntu-latest
+    permissions:
+      contents: write
+    steps:
+      - uses: actions/checkout@v4
 
-  #     - name: Create a new version branch
-  #       env:
-  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-  #       shell: bash
-  #       run: |
-  #         git checkout -b ${{ needs.detect-versions.outputs.version }}
-  #         git push -u origin ${{ needs.detect-versions.outputs.version }}
+      - name: Create a new version branch
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        shell: bash
+        run: |
+          git checkout -b ${{ needs.detect-versions.outputs.version }}
+          git push -u origin ${{ needs.detect-versions.outputs.version }}
diff --git a/.github/workflows/validate.yml b/.github/workflows/validate.yml
--- a/.github/workflows/validate.yml
+++ b/.github/workflows/validate.yml
@@ -62,18 +62,23 @@ jobs:
     steps:
       - uses: actions/checkout@v4
 
-      - uses: actions/setup-python@v5
-
-      - name: Install dependencies
-        run: |
-          pip install .[dev]
+      - name: Install Python 3.12
+        uses: actions/setup-python@v5
+        with:
+          python-version: '3.12'
 
       - name: Build docs
+        shell: bash
         run: |
+          # GHA does `set -e` for us, but we expect the grep below to fail. Thus, we must `set +e` here.
+          set +e
+          pip install .[dev]
           cd docs
-          make clean build |& tee make.log
+          make clean html |& tee make.log
           grep '\(ERROR\|WARNING\)' make.log
           if [ $? -eq 0 ]; then
             echo "Problems found in docs build"
             exit 1
+          else
+            exit 0
           fi
